### ISSUE TITLE
Can i get any inverter data using this? Can anyone guide me how I can fetch inverter data into Javascript?

### ISSUE THREAD

**Issue by syedzubair23** [benzino77/solaredge-rest-api#1]

**Comment by benzino77** [comment]
What you mean by that? It retrieves data from inverter itself via modbus.

**Comment by syedzubair23** [comment]
I want to display my solar inverter data into my website dashboard

**Comment by benzino77** [comment]
I still don't get the point...
This is a project that lets you make a REST request and get Inverter data as JSON. 
You can do with this data whatever you want, ie. display it on your website.

Have you read the REDME information for this project?

**Comment by syedzubair23** [comment]
Its REST api to Solaredge inverter, But mine inverter is different. Its inverex 6kw SP-hybrid inverter

**Comment by benzino77** [comment]
If you do not have SolarEdge Inverter with MODBUS over TCP enabled, than this project is not for you. It will work only with SolrEdge Inverters.

**Comment by syedzubair23** [comment]
Thanks! That's what I wanted to ask
